apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-opt-conf
  namespace: latam-challenge
data: 
  nginx.conf: |-
    
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        client_max_body_size 8M;
        proxy_read_timeout 600s;
        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
        send_timeout 600s;

        keepalive_timeout  65;

        upstream api {
            server 127.0.0.1:5000;
        }

        server {
            listen 80;
            location / {
              proxy_pass http://api/;
            }

            location /hubs/outoutput {
              proxy_pass http://api/hubs/outoutput;
              proxy_http_version 1.1;
              proxy_set_header Upgrade "upgrade";
              proxy_set_header Connection "upgrade";
              proxy_cache_bypass "upgrade";
              }
        } 

        include /etc/nginx/conf.d/*.conf;
    }