name: apigateway-main

env:
  INFRA_DIR: apigateway

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/${INFRA_DIR}.yml"
      - "infra/${INFRA_DIR}/**"
      - "infra/terraform/${INFRA_DIR}/**"
    branches:
      - "main"

jobs:
  apigateway-nonprod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.2"
      - name: Write config files
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: | 
          echo "$ENV_FILE" > creds.json
      - name: Terraform Format
        run: terraform fmt
      - name: Terraform Validate 
        run: terraform validate
      - name: Terraform Plan 
        run: |
          cd infra/terraform/${{env.INFRA_DIR}}
          terraform init -get=true -force-copy -backend-config=../../${{env.INFRA_DIR}}/backend.tfvars
          terraform plan -var-file=../../${{env.INFRA_DIR}}/terraform.tfvars 